### ISSUE TITLE
Puuttuva js-kansio asseteissa

### ISSUE THREAD

**Issue by veke** [iuuso/KV-challenge#1]
Hei, laitatko vielä tuon js-kansion ja filut tuonne assetteihin, niin toimii paremmin.

**Comment by iuuso** [comment]
Ohops, laitanpa heti kun saan koneen käsiini. Muutto kesken ja kone on jo
toisessa osoitteessa.

**Comment by veke** [comment]
Jeba.

**Comment by iuuso** [comment]
Puuttuvat tiedostot lisätty.
